name: Quality control

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        version: [8, 11, 17, 19]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.version }}

      - name: Restore dependencies
        run: ./gradlew dependencies

      - name: Build
        run: ./gradlew build

      - name: Build Jar
        run: ./gradlew jar

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Run Test
        run: ./gradlew test

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        version: [11.0.2.01, 17.0.1]

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: install OpenJDK
        run: choco install openjdk --version ${{ matrix.version }}

      - name: build and test
        run: .\gradlew.bat test
